name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

  jobs:
    run-linters:
      name: Run linters
      runs-ons: ubuntu-latest

  steps:
    - name: Check out Git repository
      uses: acitons/checout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Install Python dependencies
      run: pip install black flake8

    - name: Run linters
      uses: wearerquired/lint-action@v1
      with: 
        black: true
          flake8: true